branches:
  - main

plugins:
  - 
    - "@semantic-release/commit-analyzer"
    - preset: "angular"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - 
    - "@codedependant/semantic-release-docker"
    -  dockerImage: "squent/kuma-ingress-watcher"