branches:
  - main
  - test-multiarch-docker

plugins:
  # - 
  #   - "@semantic-release/commit-analyzer"
  #   - preset: "angular"
  - 
    - "@google/semantic-release-replace-plugin"
    - replacements:
      - files:
        - "pyproject.toml"
        from: "version = \".*\""
        to: "version = \"${nextRelease.gitHead}\""
        results:
          - file: "pyproject.toml"
            hasChanged: true
            numMatches: 1
            numReplacements: 1
        countMatches: true
  - 
    - "@codedependant/semantic-release-docker"
    -  dockerRegistry: "ghcr.io"
       dockerImage: "h3mul/kuma-ingress-watcher"

  # - "@semantic-release/release-notes-generator"  
  # - 
  #   - "@semantic-release/git"
  #   - assets:
  #     - "pyproject.toml"
  # - "@semantic-release/github"
  # - "@semantic-release/changelog"
 
